Repository SB01-Team09/sb01-otboo-team09, pull requests merged in 2025-07, with the labels that each got.

#48 Feature: Prometheus + Grafana 연동
  .gitignore
  build.gradle
  docker-compose-monitoring.yml
  prometheus.yml
  src/main/java/com/part4/team09/otboo/config/P6spy/P6spyConfig.java
  src/main/java/com/part4/team09/otboo/config/P6spy/P6spyMeterRegistryConfig.java
  src/main/java/com/part4/team09/otboo/config/P6spy/P6spyPrettySqlFormatter.java
  src/main/java/com/part4/team09/otboo/module/common/monitoring/BatchMonitoringListener.java
  src/main/java/com/part4/team09/otboo/module/domain/location/batch/LocationBatch.java
  src/main/java/com/part4/team09/otboo/module/domain/weather/external/WeatherApiClient.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: ✨feature

#46 Feature: 유저 권한 및 잠금 상태 변경
  src/main/java/com/part4/team09/otboo/module/common/exception/CommonErrorCode.java
  src/main/java/com/part4/team09/otboo/module/common/exception/GlobalExceptionHandler.java
  src/main/java/com/part4/team09/otboo/module/domain/follow/mapper/FollowMapper.java
  src/main/java/com/part4/team09/otboo/module/domain/follow/service/FollowService.java
  src/main/java/com/part4/team09/otboo/module/domain/user/controller/UserController.java
  src/main/java/com/part4/team09/otboo/module/domain/user/dto/UserLockUpdateRequest.java
  src/main/java/com/part4/team09/otboo/module/domain/user/dto/UserRoleUpdateRequest.java
  src/main/java/com/part4/team09/otboo/module/domain/user/entity/User.java
  src/main/java/com/part4/team09/otboo/module/domain/user/exception/EmailAlreadyExistsException.java
  src/main/java/com/part4/team09/otboo/module/domain/user/exception/UserException.java
  src/main/java/com/part4/team09/otboo/module/domain/user/exception/UserNotFoundException.java
  src/main/java/com/part4/team09/otboo/module/domain/user/service/UserService.java
  src/test/java/com/part4/team09/otboo/module/domain/user/entity/UserTest.java
  src/test/java/com/part4/team09/otboo/module/domain/user/service/UserServiceTest.java
Labels: ✨feature

#51 Feature: 의상 속성 정의 조회 구현
  src/main/java/com/part4/team09/otboo/module/common/enums/SortDirection.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/controller/ClothesAttributeDefController.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/dto/request/ClothesAttributeDefFindRequest.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/dto/response/ClothesAttributeDefDtoCursorResponse.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/dto/response/ClothesDtoCursorResponse.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/mapper/ClothesAttributeDefDtoCursorResponseMapper.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/repository/SelectableValueRepository.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/repository/custom/ClothesAttributeDefRepositoryQueryDSL.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeDefService.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeInfoService.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/service/SelectableValueService.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/repository/SelectableValueRepositoryTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/repository/custom/ClothesAttributeDefRepositoryQueryDSLTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeDefServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeInfoServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/service/SelectableValueServiceTest.java
Labels: ✨feature

#56 Refactor: 의상 속성 정의 리팩토링
  src/main/java/com/part4/team09/otboo/module/domain/clothes/controller/ClothesAttributeDefController.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/exception/ClothesAttributeDef/BadRequestException.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/repository/custom/ClothesAttributeDefRepositoryQueryDSL.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeDefService.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeInfoService.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeService.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/service/SelectableValueService.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/repository/ClothesAttributeDefRepositoryTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/repository/SelectableValueRepositoryTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/repository/custom/ClothesAttributeDefRepositoryQueryDSLTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeDefServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeInfoServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/service/SelectableValueServiceTest.java
Labels: 🔧refactor

#57 Refactor: 팔로우 서비스 일부, 페이징 수정
  src/main/java/com/part4/team09/otboo/module/domain/follow/contoller/FollowController.java
  src/main/java/com/part4/team09/otboo/module/domain/follow/dto/FollowListRequest.java
  src/main/java/com/part4/team09/otboo/module/domain/follow/dto/FollowListResponse.java
  src/main/java/com/part4/team09/otboo/module/domain/follow/repository/FollowRepositoryQueryDSL.java
  src/main/java/com/part4/team09/otboo/module/domain/follow/service/FollowService.java
  src/test/java/com/part4/team09/otboo/module/domain/follow/service/FollowServiceTest.java
Labels: 🔧refactor

#63 Feature: 피드 댓글 등록 구현
  src/main/java/com/part4/team09/otboo/module/domain/feed/controller/FeedController.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/dto/CommentCreateRequest.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/dto/CommentDto.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/exception/FeedErrorCode.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/exception/FeedNotFoundException.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/mapper/CommentMapper.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/service/CommentService.java
  src/test/java/com/part4/team09/otboo/module/domain/feed/controller/FeedControllerTest.java
  src/test/java/com/part4/team09/otboo/module/domain/feed/service/CommentServiceTest.java
Labels: ✨feature

#65 Refactor: 프로필 위치 업데이트 부분 수정 및 프로필 이미지(파일) 삭제
  src/main/java/com/part4/team09/otboo/config/AppConfig.java
  src/main/java/com/part4/team09/otboo/config/AsyncConfig.java
  src/main/java/com/part4/team09/otboo/config/LocalWebMvcConfig.java
  src/main/java/com/part4/team09/otboo/module/domain/file/service/FileStorage.java
  src/main/java/com/part4/team09/otboo/module/domain/file/service/LocalFileStorage.java
  src/main/java/com/part4/team09/otboo/module/domain/location/exception/LocationNotFoundException.java
  src/main/java/com/part4/team09/otboo/module/domain/location/repository/DongRepository.java
  src/main/java/com/part4/team09/otboo/module/domain/location/repository/LocationRepository.java
  src/main/java/com/part4/team09/otboo/module/domain/user/event/UserEventListener.java
  src/main/java/com/part4/team09/otboo/module/domain/user/event/UserProfileUpdateEvent.java
  src/main/java/com/part4/team09/otboo/module/domain/user/service/UserService.java
  src/main/resources/application.yml
  src/test/java/com/part4/team09/otboo/module/domain/file/service/LocalFileStorageTest.java
  src/test/java/com/part4/team09/otboo/module/domain/user/service/UserServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/user/service/UserServiceUnitTest.java
Labels: 🔧refactor

#61 Feature: 팔로우 요약 정보 조회
  src/main/java/com/part4/team09/otboo/module/domain/follow/contoller/FollowController.java
  src/main/java/com/part4/team09/otboo/module/domain/follow/dto/FollowSummaryDto.java
  src/main/java/com/part4/team09/otboo/module/domain/follow/exception/FollowErrorCode.java
  src/main/java/com/part4/team09/otboo/module/domain/follow/exception/NegativeLimitNotAllowed.java
  src/main/java/com/part4/team09/otboo/module/domain/follow/repository/FollowRepository.java
  src/main/java/com/part4/team09/otboo/module/domain/follow/service/FollowService.java
  src/test/java/com/part4/team09/otboo/module/domain/follow/service/FollowServiceTest.java
Labels: ✨feature

#70 Feature: 의상 등록 구현
  src/main/java/com/part4/team09/otboo/module/domain/clothes/controller/ClothesController.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/exception/Clothes/ClothesNotFoundException.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/exception/ClothesErrorCode.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/exception/SelectableValue/SelectableValueNotFoundException.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/mapper/ClothesAttributeWithDefMapper.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/mapper/ClothesMapper.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeDefService.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeInfoService.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeService.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesService.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/service/SelectableValueService.java
  src/main/java/com/part4/team09/otboo/module/domain/file/FileDomain.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeDefServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeInfoServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesServiceTest.java
Labels: ✨feature

#76 Refactor: 팔로우 요약 정보 조회 캐싱 적용
  build.gradle
  src/main/java/com/part4/team09/otboo/config/AppConfig.java
  src/main/java/com/part4/team09/otboo/config/CacheConfig.java
  src/main/java/com/part4/team09/otboo/module/domain/follow/event/FollowCacheEvictListener.java
  src/main/java/com/part4/team09/otboo/module/domain/follow/event/FollowCreatedEvent.java
  src/main/java/com/part4/team09/otboo/module/domain/follow/event/FollowDeletedEvent.java
  src/main/java/com/part4/team09/otboo/module/domain/follow/service/FollowService.java
  src/main/resources/application.yml
  src/test/java/com/part4/team09/otboo/module/domain/follow/service/FollowServiceTest.java
Labels: 🔧refactor

#78 Feature: 피드 삭제
  src/main/java/com/part4/team09/otboo/module/domain/feed/controller/FeedController.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/repository/CommentRepository.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/repository/OotdRepository.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/service/CommentService.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/service/FeedService.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/service/OotdService.java
  src/test/java/com/part4/team09/otboo/module/domain/feed/controller/FeedControllerTest.java
  src/test/java/com/part4/team09/otboo/module/domain/feed/service/FeedServiceTest.java
Labels: ✨feature

#82 Feature: 의상 수정
  src/main/java/com/part4/team09/otboo/module/domain/clothes/controller/ClothesController.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/entity/Clothes.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/repository/ClothesAttributeRepository.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeService.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesService.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeInfoServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesServiceTest.java
Labels: ✨feature

#89 Feature: 외부 api 테스트 코드 작성
  src/test/java/com/part4/team09/otboo/config/LocationApiClientTestConfig.java
  src/test/java/com/part4/team09/otboo/config/WeatherApiClientTestConfig.java
  src/test/java/com/part4/team09/otboo/module/domain/location/external/LocationApiClientTest.java
  src/test/java/com/part4/team09/otboo/module/domain/weather/external/WeatherApiClientTest.java
Labels: test

#87 Refactor: feed mapper 개선
  src/main/java/com/part4/team09/otboo/module/domain/clothes/exception/SelectableValue/SelectableValueNotFoundException.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/repository/ClothesAttributeRepository.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/repository/ClothesRepository.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/controller/FeedController.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/dto/FeedDto.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/dto/request/CommentCreateRequest.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/dto/request/FeedCreateRequest.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/dto/request/FeedUpdateRequest.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/mapper/FeedDtoAssembler.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/mapper/FeedMapper.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/mapper/OotdMapper.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/service/CommentService.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/service/FeedService.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/service/LikeService.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/service/OotdService.java
  src/main/java/com/part4/team09/otboo/module/domain/weather/dto/response/WeatherSummaryDto.java
  src/main/java/com/part4/team09/otboo/module/domain/weather/mapper/WeatherMapper.java
  src/test/java/com/part4/team09/otboo/module/domain/feed/controller/FeedControllerTest.java
  src/test/java/com/part4/team09/otboo/module/domain/feed/service/CommentServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/feed/service/FeedServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/feed/service/LikeServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/feed/service/OotdServiceTest.java
Labels: 🔧refactor

#91 Feature: 로그인, Access 토큰 조회, 토큰 재발급
  src/main/java/com/part4/team09/otboo/config/SecurityConfig.java
  src/main/java/com/part4/team09/otboo/module/common/exception/GlobalExceptionHandler.java
  src/main/java/com/part4/team09/otboo/module/common/security/CustomUserDetails.java
  src/main/java/com/part4/team09/otboo/module/common/security/CustomUserDetailsService.java
  src/main/java/com/part4/team09/otboo/module/common/security/Filter/JsonLoginAuthenticationFilter.java
  src/main/java/com/part4/team09/otboo/module/common/security/Filter/JwtAuthenticationFilter.java
  src/main/java/com/part4/team09/otboo/module/common/security/exception/InvalidJwtFormatException.java
  src/main/java/com/part4/team09/otboo/module/common/security/exception/InvalidJwtSignatureException.java
  src/main/java/com/part4/team09/otboo/module/common/security/exception/JwtAuthenticationException.java
  src/main/java/com/part4/team09/otboo/module/common/security/exception/JwtExpiredException.java
  src/main/java/com/part4/team09/otboo/module/common/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/part4/team09/otboo/module/common/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/part4/team09/otboo/module/common/security/handler/JsonLoginFailureHandler.java
  src/main/java/com/part4/team09/otboo/module/common/security/handler/JsonLoginSuccessHandler.java
  src/main/java/com/part4/team09/otboo/module/common/security/jwt/AuthToken.java
  src/main/java/com/part4/team09/otboo/module/common/security/jwt/AuthTokenRepository.java
  src/main/java/com/part4/team09/otboo/module/common/security/jwt/GeneratedToken.java
  src/main/java/com/part4/team09/otboo/module/common/security/jwt/JwtProperty.java
  src/main/java/com/part4/team09/otboo/module/common/security/jwt/JwtTokenProvider.java
  src/main/java/com/part4/team09/otboo/module/common/util/IpUtils.java
  src/main/java/com/part4/team09/otboo/module/domain/auth/contoller/AuthController.java
  src/main/java/com/part4/team09/otboo/module/domain/auth/dto/AuthUserDto.java
  src/main/java/com/part4/team09/otboo/module/domain/auth/dto/LoginRequest.java
  src/main/java/com/part4/team09/otboo/module/domain/auth/exception/AccountLockedException.java
  src/main/java/com/part4/team09/otboo/module/domain/auth/exception/AuthErrorCode.java
  src/main/java/com/part4/team09/otboo/module/domain/auth/exception/AuthException.java
  src/main/java/com/part4/team09/otboo/module/domain/auth/exception/InvalidTokenException.java
  src/main/java/com/part4/team09/otboo/module/domain/auth/mapper/AuthUserMapper.java
  src/main/java/com/part4/team09/otboo/module/domain/auth/service/AuthService.java
  src/main/java/com/part4/team09/otboo/module/domain/user/controller/AuthController.java
  src/main/java/com/part4/team09/otboo/module/domain/user/repository/UserRepository.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/schema.sql
  src/test/java/com/part4/team09/otboo/module/common/security/AuthIntegrationTest.java
  src/test/java/com/part4/team09/otboo/module/domain/auth/service/AuthServiceTest.java
Labels: ✨feature

#99 Feature: 좋아요 삭제
  src/main/java/com/part4/team09/otboo/module/domain/feed/controller/FeedController.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/exception/FeedErrorCode.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/exception/feed/FeedNotFoundException.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/exception/like/LikeAlreadyExistsException.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/exception/like/LikeNotFoundException.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/mapper/FeedDtoAssembler.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/repository/LikeRepository.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/service/CommentService.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/service/FeedService.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/service/LikeService.java
  src/test/java/com/part4/team09/otboo/module/domain/feed/controller/FeedControllerTest.java
  src/test/java/com/part4/team09/otboo/module/domain/feed/service/CommentServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/feed/service/FeedServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/feed/service/LikeServiceTest.java
Labels: ✨feature

#104 Feature: 날씨 정보 저장 배치 테스트 코드 작성
  src/main/java/com/part4/team09/otboo/module/domain/weather/batch/WeatherReader.java
  src/test/java/com/part4/team09/otboo/config/MeterRegistryTestConfig.java
  src/test/java/com/part4/team09/otboo/module/domain/weather/batch/WeatherProcessorTest.java
  src/test/java/com/part4/team09/otboo/module/domain/weather/batch/WeatherReaderTest.java
  src/test/java/com/part4/team09/otboo/module/domain/weather/batch/WeatherWriterTest.java
  src/test/resources/weather-api-response.json
Labels: test

#109 Feature: 강제 로그아웃 적용 및 메서드 보안 설정
  src/main/java/com/part4/team09/otboo/config/AdminInitializer.java
  src/main/java/com/part4/team09/otboo/config/SecurityConfig.java
  src/main/java/com/part4/team09/otboo/module/common/exception/GlobalExceptionHandler.java
  src/main/java/com/part4/team09/otboo/module/common/security/Filter/JwtAuthenticationFilter.java
  src/main/java/com/part4/team09/otboo/module/common/security/exception/AccessTokenNotFoundException.java
  src/main/java/com/part4/team09/otboo/module/common/security/exception/AccessTokenReplacedException.java
  src/main/java/com/part4/team09/otboo/module/common/security/jwt/AuthTokenRepository.java
  src/main/java/com/part4/team09/otboo/module/common/security/jwt/JwtTokenProvider.java
  src/main/java/com/part4/team09/otboo/module/domain/auth/contoller/AuthController.java
  src/main/java/com/part4/team09/otboo/module/domain/auth/dto/AuthUserDto.java
  src/main/java/com/part4/team09/otboo/module/domain/auth/exception/AuthErrorCode.java
  src/main/java/com/part4/team09/otboo/module/domain/auth/exception/AuthenticationRequiredException.java
  src/main/java/com/part4/team09/otboo/module/domain/auth/exception/MissingRefreshTokenException.java
  src/main/java/com/part4/team09/otboo/module/domain/auth/service/AuthService.java
  src/main/java/com/part4/team09/otboo/module/domain/user/controller/UserController.java
  src/main/java/com/part4/team09/otboo/module/domain/user/service/UserService.java
  src/main/resources/static/assets/index-DhSJDZtc.js
  src/main/resources/static/assets/index-NzgYvg84.js
  src/main/resources/static/closet-hanger-logo.png
  src/main/resources/static/index.html
  src/main/resources/static/vite.svg
  src/test/java/com/part4/team09/otboo/module/domain/user/service/UserServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/user/service/UserServiceUnitTest.java
Labels: ✨feature

#105 Refactor: Feed 관련 로직에 스프링 시큐리티 적용
  src/main/java/com/part4/team09/otboo/module/domain/feed/controller/FeedController.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/permission/FeedPermissionEvaluator.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/service/FeedService.java
  src/test/java/com/part4/team09/otboo/module/domain/feed/controller/FeedControllerTest.java
Labels: 🔧refactor

#122 Refactor: 의상 및 의상 속성 개선
  src/main/java/com/part4/team09/otboo/module/domain/clothes/assembler/ClothesAttributeDefDtoAssembler.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/assembler/ClothesAttributeWithDefDtoAssembler.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/controller/ClothesAttributeDefController.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/dto/request/ClothesCreateRequest.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/dto/request/ClothesUpdateRequest.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/entity/Clothes.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/mapper/ClothesAttributeWithDefMapper.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/repository/ClothesAttributeRepository.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/repository/custom/ClothesAttributeDefRepositoryQueryDSL.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/repository/custom/ClothesRepositoryQueryDSL.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeDefService.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeInfoService.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeService.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesService.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/service/SelectableValueService.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/repository/OotdRepository.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/assembler/ClothesAttributeDefDtoAssemblerTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/assembler/ClothesAttributeWithDefDtoAssemblerTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/repository/ClothesAttributeRepositoryTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/repository/ClothesRepositoryTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/repository/custom/ClothesAttributeDefRepositoryQueryDSLTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/repository/custom/ClothesRepositoryQueryDSLTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeDefServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeInfoServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesServiceTest.java
Labels: 🔧refactor

#123 Feature: 피드 목록 조회
  src/main/java/com/part4/team09/otboo/config/CacheConfig.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/controller/FeedController.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/dto/FeedDtoCursorResponse.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/dto/request/FeedListRequest.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/event/FeedCacheEvictListener.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/event/FeedCreatedEvent.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/event/FeedDeletedEvent.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/repository/FeedRepositoryQueryDSL.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/service/FeedService.java
  src/main/java/com/part4/team09/otboo/module/domain/follow/contoller/FollowController.java
  src/main/java/com/part4/team09/otboo/module/domain/follow/event/FollowCacheEvictListener.java
  src/main/java/com/part4/team09/otboo/module/domain/follow/service/FollowService.java
  src/main/resources/application.yml
  src/test/java/com/part4/team09/otboo/module/domain/feed/service/FeedServiceIntegrationTest.java
  src/test/java/com/part4/team09/otboo/module/domain/feed/service/FeedServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/follow/service/FollowServiceTest.java
  src/test/resources/application-test.yml
Labels: ✨feature

#126 Refactor: DM 목록 조회 assembler 적용
  src/main/java/com/part4/team09/otboo/module/domain/directmessage/mapper/DirectMessageDtoAssembler.java
  src/main/java/com/part4/team09/otboo/module/domain/directmessage/service/DirectMessageService.java
Labels: 🔧refactor

#127 Refactor: 유저 API 접근 권한 설정 및 테스트
  src/main/java/com/part4/team09/otboo/module/common/exception/GlobalExceptionHandler.java
  src/main/java/com/part4/team09/otboo/module/common/security/handler/CustomLogoutHandler.java
  src/main/java/com/part4/team09/otboo/module/common/security/handler/JsonLoginSuccessHandler.java
  src/main/java/com/part4/team09/otboo/module/domain/user/controller/UserController.java
  src/test/java/com/part4/team09/otboo/module/domain/user/controller/UserControllerTest.java
Labels: test

#130 Feature: 의상 추천 알고리즘 및 조회 API 구현
  src/main/java/com/part4/team09/otboo/config/RestClientConfig.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/repository/custom/ClothesRepositoryQueryDSL.java
  src/main/java/com/part4/team09/otboo/module/domain/recommendation/controller/RecommendationController.java
  src/main/java/com/part4/team09/otboo/module/domain/recommendation/dto/ClothingOption.java
  src/main/java/com/part4/team09/otboo/module/domain/recommendation/dto/request/ContentRequest.java
  src/main/java/com/part4/team09/otboo/module/domain/recommendation/dto/response/GeminiResponse.java
  src/main/java/com/part4/team09/otboo/module/domain/recommendation/dto/response/RecommendationClothesAttributeDto.java
  src/main/java/com/part4/team09/otboo/module/domain/recommendation/dto/response/RecommendationClothesDto.java
  src/main/java/com/part4/team09/otboo/module/domain/recommendation/dto/response/RecommendationDto.java
  src/main/java/com/part4/team09/otboo/module/domain/recommendation/external/LLMApiClient.java
  src/main/java/com/part4/team09/otboo/module/domain/recommendation/service/RecommendationService.java
Labels: ✨feature

#131 Refactor: 의상 로직 수정
  src/main/java/com/part4/team09/otboo/config/MDCLoggingInterceptor.java
  src/main/java/com/part4/team09/otboo/config/QueryDslConfig.java
  src/main/java/com/part4/team09/otboo/config/SecurityConfig.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/assembler/ClothesAttributeDefDtoAssembler.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/assembler/ClothesAttributeWithDefDtoAssembler.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/assembler/ClothesDtoAssembler.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/controller/ClothesAttributeDefController.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/controller/ClothesController.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/dto/data/ClothesDto.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/dto/data/ClothesWithAttributesDto.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/entity/Clothes.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/mapper/ClothesMapper.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/repository/ClothesAttributeDefRepository.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/repository/ClothesRepository.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/repository/custom/CustomClothesAttributeDefRepository.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/repository/custom/CustomClothesRepository.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/repository/custom/impl/CustomClothesAttributeDefRepositoryImpl.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/repository/custom/impl/CustomClothesRepositoryImpl.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeDefService.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeInfoService.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeService.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesService.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/service/SelectableValueService.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/assembler/ClothesAttributeDefDtoAssemblerTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/repository/ClothesAttributeDefRepositoryTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/repository/ClothesAttributeRepositoryTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/repository/ClothesRepositoryTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/repository/SelectableValueRepositoryTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/repository/custom/ClothesAttributeDefRepositoryQueryDSLTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/repository/custom/ClothesRepositoryQueryDSLTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeDefServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesAttributeServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/weather/batch/WeatherWriterTest.java
Labels: 🔧refactor

#134 Feature: 알림 생성
  src/main/java/com/part4/team09/otboo/module/domain/follow/repository/FollowRepository.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/dto/NotificationDto.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/dto/request/NotificationCreateAllRequest.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/dto/request/NotificationCreateFollowerRequest.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/dto/request/NotificationCreateLocationRequest.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/dto/request/NotificationCreateMultipleRequest.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/dto/request/NotificationCreateRequest.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/event/ClothesAttributeDefCreatedEvent.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/event/ClothesAttributeDefUpdatedEvent.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/event/DirectMessageReceivedEvent.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/event/FeedCommentedEvent.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/event/FeedCreatedEvent.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/event/FeedLikedEvent.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/event/FollowedEvent.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/event/Listener/NotificationEventListener.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/event/Listener/SseEventListener.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/event/NotificationCreatedEvent.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/event/NotificationCreatedMultipleEvent.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/event/PrecipitationStartedEvent.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/event/RapidTemperatureDropEvent.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/event/RapidTemperatureRiseEvent.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/event/RoleChangedEvent.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/mapper/NotificationMapper.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/service/NotificationService.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/sse/SseController.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/sse/SseEmitterRepository.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/sse/SseService.java
  src/main/java/com/part4/team09/otboo/module/domain/user/repository/UserRepository.java
  src/main/resources/application.yml
  src/test/java/com/part4/team09/otboo/module/domain/notification/service/NotificationServiceTest.java
Labels: ✨feature

#136 Feature: 알림 읽음처리
  src/main/java/com/part4/team09/otboo/module/domain/notification/controller/NotificationController.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/exception/NotificationErrorCode.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/exception/NotificationException.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/exception/NotificationNotFoundException.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/permission/NotificationPermissionEvaluator.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/service/NotificationService.java
  src/test/java/com/part4/team09/otboo/module/domain/notification/controller/NotificationControllerTest.java
  src/test/java/com/part4/team09/otboo/module/domain/notification/service/NotificationServiceTest.java
Labels: ✨feature

#142 Feature: DM 송/수신
  build.gradle
  src/main/java/com/part4/team09/otboo/config/StompHandler.java
  src/main/java/com/part4/team09/otboo/config/WebSocketConfig.java
  src/main/java/com/part4/team09/otboo/module/common/security/jwt/JwtTokenProvider.java
  src/main/java/com/part4/team09/otboo/module/domain/directmessage/controller/DirectMessageController.java
  src/main/java/com/part4/team09/otboo/module/domain/directmessage/controller/DirectMessageWebSocketController.java
  src/main/java/com/part4/team09/otboo/module/domain/directmessage/dto/DirectMessageDto.java
  src/main/java/com/part4/team09/otboo/module/domain/directmessage/dto/DirectMessageSendPayload.java
  src/main/java/com/part4/team09/otboo/module/domain/directmessage/dto/request/DirectMessageCreateRequest.java
  src/main/java/com/part4/team09/otboo/module/domain/directmessage/mapper/DirectMessageDtoAssembler.java
  src/main/java/com/part4/team09/otboo/module/domain/directmessage/mapper/DirectMessageMapper.java
  src/main/java/com/part4/team09/otboo/module/domain/directmessage/service/DirectMessageService.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/service/FeedService.java
  src/main/java/com/part4/team09/otboo/module/domain/user/dto/UserSummary.java
  src/main/java/com/part4/team09/otboo/module/domain/user/mapper/UserSummaryMapper.java
  src/main/resources/application-dev.yml
  src/test/java/com/part4/team09/otboo/module/domain/directmessage/service/DirectMessageServiceTest.java
Labels: ✨feature

#149 Feature: 피드의 좋아요, 댓글 수 증감
  src/main/java/com/part4/team09/otboo/module/domain/feed/entity/Feed.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/service/CommentService.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/service/LikeService.java
  src/test/java/com/part4/team09/otboo/module/domain/feed/service/CommentServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/feed/service/LikeServiceTest.java
Labels: ✨feature

#169 Refactor: 알림 시스템에 Kafka 도입
  build.gradle
  src/main/java/com/part4/team09/otboo/module/domain/notification/event/Listener/KafkaHandler.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/event/Listener/NotificationEventListener.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: 🔧refactor

#174 Refactor: 의상 관련 컨트롤러 테스트
  src/test/java/com/part4/team09/otboo/module/domain/clothes/controller/ClothesAttributeDefControllerTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/controller/ClothesControllerTest.java
Labels: 🔧refactor

#179 Deploy: nginx.conf 및 kafka 연결
  Dockerfile
  nginx/Dockerfile
  nginx/nginx.conf
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 🚀deploy

#187 Refactor: url로 의상 정보 가져오기 수정
  src/main/java/com/part4/team09/otboo/module/domain/clothes/controller/ClothesController.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/dto/data/ClothesDto.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/dto/request/ClothesCreateRequest.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/service/ClothesService.java
Labels: 🔧refactor

#190 Feature: 알림 목록 조회 및 DM 목록 조회 테스트
  src/main/java/com/part4/team09/otboo/module/domain/directmessage/controller/DirectMessageController.java
  src/main/java/com/part4/team09/otboo/module/domain/directmessage/repository/DirectMessageRepositoryQueryDSL.java
  src/main/java/com/part4/team09/otboo/module/domain/directmessage/service/DirectMessageService.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/controller/NotificationController.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/dto/NotificationDtoCursorResponse.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/repository/NotificationRepositoryQueryDSL.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/service/NotificationService.java
  src/test/java/com/part4/team09/otboo/module/domain/directmessage/repository/DirectMessageRepositoryQueryDSLTest.java
  src/test/java/com/part4/team09/otboo/module/domain/directmessage/service/DirectMessageServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/follow/service/FollowServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/notification/repository/NotificationRepositoryQueryDSLTest.java
  src/test/java/com/part4/team09/otboo/module/domain/notification/service/NotificationServiceTest.java
Labels: ✨feature

#194 Chore: jacoco 커버리지 제외 설정
  build.gradle
Labels: 🍪chore

#198 Test: Weather domain test coverage 향상
  build.gradle
  src/main/java/com/part4/team09/otboo/module/domain/weather/batch/WeatherCache.java
  src/main/java/com/part4/team09/otboo/module/domain/weather/batch/retry/RetryBatch.java
  src/test/java/com/part4/team09/otboo/module/domain/weather/controller/WeatherControllerTest.java
  src/test/java/com/part4/team09/otboo/module/domain/weather/scheduler/WeatherNotificationSchedulerTest.java
Labels: test

#204 Refactor: 의상 조회 성능 최적화
  src/main/resources/schema.sql
Labels: 🔧refactor

#202 Test: Security, File, Mail test 추가
  build.gradle
  src/main/java/com/part4/team09/otboo/config/SecurityConfig.java
  src/main/java/com/part4/team09/otboo/module/common/exception/GlobalExceptionHandler.java
  src/main/java/com/part4/team09/otboo/module/common/security/Filter/JwtAuthenticationFilter.java
  src/main/java/com/part4/team09/otboo/module/common/security/LoginType.java
  src/main/java/com/part4/team09/otboo/module/common/security/basic/CustomDaoAuthenticationProvider.java
  src/main/java/com/part4/team09/otboo/module/common/security/basic/CustomUserDetailsService.java
  src/main/java/com/part4/team09/otboo/module/common/security/basic/JsonLoginFailureHandler.java
  src/main/java/com/part4/team09/otboo/module/common/security/basic/JsonLoginSuccessHandler.java
  src/main/java/com/part4/team09/otboo/module/common/security/constants/AuthCookieNames.java
  src/main/java/com/part4/team09/otboo/module/common/security/constants/LoginType.java
  src/main/java/com/part4/team09/otboo/module/common/security/handler/CustomLogoutHandler.java
  src/main/java/com/part4/team09/otboo/module/common/security/oauth/CustomOAuth2SuccessHandler.java
  src/main/java/com/part4/team09/otboo/module/common/security/oauth/CustomOAuth2UserService.java
  src/main/java/com/part4/team09/otboo/module/common/security/oauth/OAuthAttributes.java
  src/main/java/com/part4/team09/otboo/module/common/security/oauth/OAuthProviderRepository.java
  src/main/java/com/part4/team09/otboo/module/common/security/oauth/entity/OAuthProvider.java
  src/main/java/com/part4/team09/otboo/module/common/security/userdetails/CustomOAuth2User.java
  src/main/java/com/part4/team09/otboo/module/common/security/userdetails/CustomUserDetails.java
  src/main/java/com/part4/team09/otboo/module/common/security/userdetails/CustomUserPrincipal.java
  src/main/java/com/part4/team09/otboo/module/common/util/CookieUtil.java
  src/main/java/com/part4/team09/otboo/module/domain/auth/contoller/AuthController.java
  src/main/java/com/part4/team09/otboo/module/domain/clothes/controller/ClothesController.java
  src/main/java/com/part4/team09/otboo/module/domain/directmessage/controller/DirectMessageController.java
  src/main/java/com/part4/team09/otboo/module/domain/directmessage/service/DirectMessageService.java
  src/main/java/com/part4/team09/otboo/module/domain/feed/controller/FeedController.java
  src/main/java/com/part4/team09/otboo/module/domain/follow/contoller/FollowController.java
  src/main/java/com/part4/team09/otboo/module/domain/follow/event/FollowCacheEvictListener.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/controller/NotificationController.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/sse/SseController.java
  src/main/java/com/part4/team09/otboo/module/domain/recommendation/controller/RecommendationController.java
  src/main/java/com/part4/team09/otboo/module/domain/user/controller/UserController.java
  src/test/java/com/part4/team09/otboo/module/common/security/AuthIntegrationTest.java
  src/test/java/com/part4/team09/otboo/module/common/security/basic/CustomDaoAuthenticationProviderTest.java
  src/test/java/com/part4/team09/otboo/module/common/security/handler/CustomLogoutHandlerTest.java
  src/test/java/com/part4/team09/otboo/module/common/security/jwt/JwtTokenProviderTest.java
  src/test/java/com/part4/team09/otboo/module/common/security/oauth/CustomOAuth2SuccessHandlerTest.java
  src/test/java/com/part4/team09/otboo/module/common/security/oauth/CustomOAuth2UserServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/clothes/controller/ClothesControllerTest.java
  src/test/java/com/part4/team09/otboo/module/domain/directmessage/service/DirectMessageServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/feed/controller/FeedControllerTest.java
  src/test/java/com/part4/team09/otboo/module/domain/file/service/LocalFileStorageTest.java
  src/test/java/com/part4/team09/otboo/module/domain/file/service/S3FileStorageTest.java
  src/test/java/com/part4/team09/otboo/module/domain/follow/service/FollowServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/mail/service/EmailServiceTest.java
  src/test/java/com/part4/team09/otboo/module/domain/user/controller/UserControllerTest.java
Labels: test

#191 Refactor: SSE Redis 도입
  src/main/java/com/part4/team09/otboo/config/AsyncConfig.java
  src/main/java/com/part4/team09/otboo/config/RedisConfig.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/sse/RedisSseDisconnectSubscriber.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/sse/RedisSseSendSubscriber.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/sse/SseService.java
  src/test/java/com/part4/team09/otboo/config/TestSseServiceConfig.java
  src/test/java/com/part4/team09/otboo/module/common/security/AuthIntegrationTest.java
  src/test/java/com/part4/team09/otboo/module/domain/user/service/UserServiceTest.java
  src/test/resources/application-test.yml
Labels: 🔧refactor

#214 Hotfix: 배포 서비스 소셜 로그인 추적 로그 추가
  src/main/java/com/part4/team09/otboo/config/SecurityConfig.java
  src/main/java/com/part4/team09/otboo/module/common/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/part4/team09/otboo/module/common/security/oauth/CustomOAuth2SuccessHandler.java
  src/main/java/com/part4/team09/otboo/module/common/security/oauth/CustomOAuth2UserService.java
  src/main/resources/application.yml
Labels: 🍪chore

#232 Chore: 배포 시간대 KST로 수정
  src/main/java/com/part4/team09/otboo/module/domain/feed/service/FeedService.java
  src/main/resources/application.yml
  src/test/java/com/part4/team09/otboo/module/domain/feed/service/FeedServiceTest.java
Labels: 🍪chore

#231 Test: Notification 테스트
  build.gradle
  src/main/java/com/part4/team09/otboo/module/domain/notification/event/listener/KafkaHandler.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/event/listener/NotificationEventListener.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/event/listener/SseEventListener.java
  src/main/java/com/part4/team09/otboo/module/domain/notification/service/NotificationService.java
  src/main/java/com/part4/team09/otboo/module/domain/weather/scheduler/WeatherNotificationScheduler.java
  src/test/java/com/part4/team09/otboo/module/domain/feed/permission/FeedPermissionEvaluatorTest.java
  src/test/java/com/part4/team09/otboo/module/domain/notification/event/listener/NotificationEventListenerTest.java
  src/test/java/com/part4/team09/otboo/module/domain/notification/permission/NotificationPermissionEvaluatorTest.java
  src/test/java/com/part4/team09/otboo/module/domain/notification/sse/SseEmitterRepositoryTest.java
Labels: test

#238 Hotfix: OAuth 인증 성공 후 에러
  src/main/java/com/part4/team09/otboo/config/SecurityConfig.java
  src/main/java/com/part4/team09/otboo/module/common/security/oauth/CustomOAuth2SuccessHandler.java
  src/main/java/com/part4/team09/otboo/module/common/util/CookieUtil.java
Labels: 🐞bug

#239 Fix: 댓글 작성자 제대로 보이게 수정
  src/main/java/com/part4/team09/otboo/module/domain/feed/service/CommentService.java
  src/test/java/com/part4/team09/otboo/module/domain/feed/service/CommentServiceTest.java
Labels: ❗hotfix

#243 chore: 쿠키 무효화 로직 제거
  src/main/java/com/part4/team09/otboo/module/common/exception/GlobalExceptionHandler.java
Labels: 🐞bug
